import { DateTime } from 'luxon';
import type { SongFull } from '../types';
import { Md5 } from 'ts-md5';

const RELEASE_DATE_FORMAT = 'yyyy-MM-dd';
const RELEASE_YEAR_FORMAT = 'yyyy';
const RELEASE_YEAR_MONTH_FORMAT = 'yyyy-MM';

export function convertDateToObj(date: string): DateTime | undefined {
	if (/\d{4}/.exec(date) !== null) {
		return DateTime.fromFormat(date, RELEASE_YEAR_FORMAT);
	} else if (/\d{4}-\d{2}/.exec(date) !== null) {
		return DateTime.fromFormat(date, RELEASE_YEAR_MONTH_FORMAT);
	} else if (/\d{4}-\d{2}-\d{2}/.exec(date) !== null) {
		return DateTime.fromFormat(date, RELEASE_DATE_FORMAT);
	}
}

/**
 * Compares two string dates in the format of RELEASE_DATE_FORMAT, RELEASE_YEAR_FORMAT, or RELEASE_YEAR_MONTH_FORMAT
 * and determines if the left-hand side is earlier than the right-hand side, returning the result as a boolean.
 * @param dateLHS The date in RELEASE_DATE_FORMAT/RELEASE_YEAR_FORMAT/RELEASE_YEAR_MONTH_FORMAT
 *                format on the left-hand side of the comparison.
 * @param dateRHS The date in RELEASE_DATE_FORMAT/RELEASE_YEAR_FORMAT/RELEASE_YEAR_MONTH_FORMAT
 *                format on the right-hand side of the comparison.
 */
export function dateIsEarlierThan(dateLHS: string, dateRHS: string): boolean {
	const lhsConverted: DateTime | undefined = convertDateToObj(dateLHS);
	const rhsConverted: DateTime | undefined = convertDateToObj(dateRHS);

	// TODO: Add in error handling, this was invalid below:
	// if (!lhsConverted.isValid || rhsConverted.isValid) {
	//     console.error(`Failed to convert dates: ${lhsConverted} <= ${rhsConverted}`);
	//     return false
	// }
	if (lhsConverted !== undefined && rhsConverted !== undefined) {
		if (lhsConverted.toMillis() <= rhsConverted.toMillis()) {
			return true;
		}
	}
	return false;
}

/**
 * DEPRECATED: Creates a hash of a song, in the form of 'song:album:artist'.
 * @param song The song object containing a song, album, and artist
 * @returns An MD5 hash of the song, album, and artist
 */
export function hashSong(song: SongFull) {
	// TODO: Do I even need to hash this?
	return Md5.hashStr(`${song.name}:${song.album}:${song.artist}`);
}

export function hashAlbum(song: SongFull) {
	return Md5.hashStr(`${song.album}:${song.artist}`);
}

/**
 * DEPRECATED: Checks if a song has album art stored based on the hash generated by hashSong.
 * @param song The song object containing a song, album, and artist
 * @returns The URL from session storage where the album art is, or null. 
 */
export function songArtIsStored(song: SongFull): string | null {
	const songHash = hashSong(song);
	const storageURL = sessionStorage.getItem(songHash);
	if (storageURL) {
		return storageURL;
	}
	return null;
}

export function albumArtIsStored(song: SongFull): string | null {
	const albumHash = hashAlbum(song);
	const storageURL = sessionStorage.getItem(albumHash);
	if (storageURL) {
		return storageURL;
	}
	return null;
}

export function isEven(num: number): boolean {
	return num % 2 === 0;
}
